"""empty message

Revision ID: 017bdeaf668e
Revises: 4fd0f804cfba
Create Date: 2024-07-16 09:37:11.626703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017bdeaf668e'
down_revision: Union[str, None] = '4fd0f804cfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('password', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'password')
    # ### end Alembic commands ###
