"""empty message

Revision ID: 034e5fdb6f6e
Revises: 30f431f3fcc1
Create Date: 2024-07-22 13:18:31.408939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034e5fdb6f6e'
down_revision: Union[str, None] = '30f431f3fcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productions', sa.Column('animal', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'animal')
    # ### end Alembic commands ###
