"""empty message

Revision ID: 0555d5e1be2b
Revises: 66b41c1d36e6
Create Date: 2024-07-02 10:05:00.276999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0555d5e1be2b'
down_revision: Union[str, None] = '66b41c1d36e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_type', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_type', 'cost')
    # ### end Alembic commands ###
