"""empty message

Revision ID: 4fd0f804cfba
Revises: d532d30f4df2
Create Date: 2024-07-09 12:43:16.571976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd0f804cfba'
down_revision: Union[str, None] = 'd532d30f4df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productionssell', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('productionssell', sa.Column('summa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productionssell', 'summa')
    op.drop_column('productionssell', 'cost')
    # ### end Alembic commands ###
