"""empty message

Revision ID: 5d94f86eac86
Revises: 034e5fdb6f6e
Create Date: 2024-07-22 13:27:54.391449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d94f86eac86'
down_revision: Union[str, None] = '034e5fdb6f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productionssell', sa.Column('animal', sa.String(length=100), nullable=True))
    op.add_column('productionssum', sa.Column('animal', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productionssum', 'animal')
    op.drop_column('productionssell', 'animal')
    # ### end Alembic commands ###
