"""empty message

Revision ID: a13a35e57058
Revises: 549d75267d56
Create Date: 2024-07-19 13:42:38.027898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13a35e57058'
down_revision: Union[str, None] = '549d75267d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('date_created', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'date_created')
    # ### end Alembic commands ###
