"""empty message

Revision ID: d532d30f4df2
Revises: 5fa39cd7e22c
Create Date: 2024-07-08 17:03:20.560655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd532d30f4df2'
down_revision: Union[str, None] = '5fa39cd7e22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productionssell', sa.Column('date_created', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productionssell', 'date_created')
    # ### end Alembic commands ###
